# config file ~/.config/ddt/config.yml
--- 
database:
   basename: easy-dhcp-dns
   ext: conf
   folder: /usr/local/dhcp-dns-tools
   backup: /usr/local/dhcp-dns-tools/backup  

generate:  
   dhcp: /usr/local/dhcp-dns-tools/dhcp
   dns: /usr/local/dhcp-dns-tools/dns
   radius: /usr/local/dhcp-dns-tools/radius

script:
   update-dhcp: /usr/local/bin/update-dhcp-server
   update-radius: /usr/local/bin/update-radius-server
