#!/bin/bash
#
# 2018/06/19 Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>

trap '[ -n "${tmp_folder}" -a -d "${tmp_folder}" ] && rm -rf "${tmp_folder}"' QUIT

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export LANG=C

tmp_folder=$(mktemp --directory /tmp/ddt-XXXXXX)
[ -n "${tmp_folder}" -a -d "${tmp_folder}" ] || exit 1

# Set Name and Version
PKG_NAME=ddt
CODE_VERSION=$(grep 'version->declare' ddt | cut -f 2 -d "'") #'
PKG_VERSION=1

# Create future tree
mkdir -p ${tmp_folder}/usr/bin
mkdir -p ${tmp_folder}/usr/share/man/man1
mkdir -p ${tmp_folder}/usr/share/ddt
mkdir -p ${tmp_folder}/etc/bash_completion.d
cp ddt                  ${tmp_folder}/usr/bin/
cp ddt.1.gz             ${tmp_folder}/usr/share/man/man1/
cp LICENSE.txt          ${tmp_folder}/usr/share/ddt/
cp config.sample.yml    ${tmp_folder}/usr/share/ddt/
cp ddt.bash_completion  ${tmp_folder}/etc/bash_completion.d/
(cd ${tmp_folder}/usr/bin;            ln -s ddt      dhcp-dns-tools)
(cd ${tmp_folder}/usr/share/man/man1; ln -s ddt.1.gz dhcp-dns-tools.1.gz)
chmod -R a+rx        ${tmp_folder}/usr/bin/ddt
chmod -R a+rX,go-w   ${tmp_folder}/usr
chmod -R a+rX,go-w   ${tmp_folder}/etc

# Data archive
rm -f ${tmp_folder}/data.tar.gz
(cd ${tmp_folder}; tar --owner root --group root -czf data.tar.gz ./usr ./etc)

# Control file
cat <<END > ${tmp_folder}/control
Package: ${PKG_NAME}
Version: ${CODE_VERSION}-${PKG_VERSION}
Section: utils
Tag: implemented-in::perl, interface::commandline, role::program
Priority: optional
Depends: perl, perl-base, perl-modules, libyaml-syck-perl, libnet-netmask-perl, libreadonly-perl, libfile-touch-perl, libtext-table-perl, libnetaddr-ip-perl
Suggests: libyaml-shell-perl | yamllint, perl-doc, isc-dhcp-server, bind9
Architecture: all
Installed-Size: $(du -ks ${tmp_folder}|cut -f 1)
Maintainer: Gabriel Moreau <Gabriel.Moreau@univ-grenoble-alpes.fr>
Description: dhcp-dns-tools management of computer names and IP addresses
 DDT is an acronym for DHCP-DNS-Tools.
 In practise, DDT is an IP Address Management (IPAM) service.
 It has been used in the LEGI laboratory for over 10 years.
 ddt (dhcp-dns-tools) is a small tool to maintain a set of computers/IP.
 In order to help you in this task, ddt command has a set of action
 to generated DHCP and DNS configuration files.
 .
 The tool is quite effective and tries to keep things simple
 but easily configurable for your site like a swiss army knife.
 Everything is saved in a YAML database
 and entries could be added, deleted, or modified by the command line.
Homepage: https://gricad-gitlab.univ-grenoble-alpes.fr/legi/soft/trokata/ddt
END

# Control archive
rm -f ${tmp_folder}/control.tar.gz
(cd ${tmp_folder}; tar --owner root --group root -czf control.tar.gz control)

# Format deb package
echo 2.0 > ${tmp_folder}/debian-binary

# Create package (control before data)
ar -r ${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb ${tmp_folder}/debian-binary ${tmp_folder}/control.tar.gz ${tmp_folder}/data.tar.gz
      
# Clean
rm -rf ${tmp_folder}

# Prepare reprepro upload
echo "# Prepare reprepro upload"
echo "( cd /srv/www/debian/ ; reprepro includedeb wheezy   ~/wheezy/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
echo "( cd /srv/www/debian/ ; reprepro includedeb jessie   ~/jessie/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
echo "( cd /srv/www/debian/ ; reprepro includedeb stretch ~/stretch/${PKG_NAME}_${CODE_VERSION}-${PKG_VERSION}_all.deb )"
echo "( cd /srv/www/debian/ ; reprepro dumpreferences ) | grep -i ddt"
